"""empty message

Revision ID: 21da8a1af934
Revises: daa73497c362
Create Date: 2020-08-30 15:02:36.981013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21da8a1af934'
down_revision = 'daa73497c362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('recipe_tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.drop_constraint('recipe_ingredients_id_fkey', 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'ingredients_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('ingredients_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('recipe_ingredients_id_fkey', 'recipe', 'ingredient', ['ingredients_id'], ['id'])
    op.drop_table('recipe_tags')
    op.drop_table('tag')
    # ### end Alembic commands ###
