"""empty message

Revision ID: 41b47521ca32
Revises: f4bcad42c2b0
Create Date: 2020-08-28 13:55:26.971417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b47521ca32'
down_revision = 'f4bcad42c2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=True)
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('recipe')
    op.drop_index('ix_recipes_lunchbox', table_name='recipes')
    op.drop_column('recipes', 'start_day_before')
    op.drop_column('recipes', 'lunchbox')
    op.drop_column('recipes', 'instructions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('instructions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('lunchbox', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('start_day_before', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_recipes_lunchbox', 'recipes', ['lunchbox'], unique=False)
    op.create_table('recipe',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipe_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('recipe_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ingredient', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('recipe_id', name='recipe_pkey'),
    sa.UniqueConstraint('ingredient', name='recipe_ingredient_key')
    )
    op.drop_table('quantity_type')
    op.drop_table('quantity')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_table('food')
    # ### end Alembic commands ###
