"""empty message

Revision ID: e57587a151a6
Revises: 101774dd0b49
Create Date: 2020-08-28 21:17:37.896534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57587a151a6'
down_revision = '101774dd0b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('name', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.drop_index('ix_recipes_recipe_name', table_name='recipes')
    op.drop_column('recipes', 'recipe_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('recipe_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.create_index('ix_recipes_recipe_name', 'recipes', ['recipe_name'], unique=False)
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_column('recipes', 'name')
    # ### end Alembic commands ###
