"""users table

Revision ID: f4bcad42c2b0
Revises: 8a8f84932643
Create Date: 2020-08-11 22:11:21.485054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bcad42c2b0'
down_revision = '8a8f84932643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('lunchbox', sa.Boolean(), nullable=True))
    op.add_column('recipes', sa.Column('start_day_before', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_recipes_lunchbox'), 'recipes', ['lunchbox'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_lunchbox'), table_name='recipes')
    op.drop_column('recipes', 'start_day_before')
    op.drop_column('recipes', 'lunchbox')
    # ### end Alembic commands ###
